version: '3.8'

services:
  gulp:
    build:
      context: ./env/gulp
    image: planning/gulp:dev
    volumes:
      - "./src/gulp:/code"
      - "./src/django/plann/static/plann:/code/output/plann"

  django:
    build:
      context: ./env/django
    image: planning/django:dev
    environment:
      DEVELOPMENT: "1"

  nginx:
    build:
      context: ./env/nginx
    image: planning/nginx:dev
