version: '3.8'

services:
  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql/data/pgdata"

  django:
    build:
      context: ./env/django
    entrypoint: /code/entrypoint.sh
    image: planning/django:dev
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - "./data/django/media:/code/media"
      - "./data/django/static:/code/static"
      - "./src/django:/code"
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19
    volumes:
      - "./data/django/media:/media:ro"
      - "./data/django/static:/static:ro"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - django
