version: '3.8'

services:
  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql/data/pgdata"

  django:
    build:
      context: ./django
    image: planning/django:dev
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - "./data/django/static:/code/static"
      - "./data/django/media:/code/media"
      - "./django/code:/code"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
