version: '3.8'

services:
  postgres:
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory='/logs'"]
    volumes:
      - "./data/postgres/logs:/logs"
    restart: always

  django:
    volumes:
      - "./data/django/logs:/logs"
    restart: always

  nginx:
    volumes:
      - "./src/nginx/nginx.override.logs.conf:/etc/nginx/nginx.override.logs.conf"
    restart: always
