version: '3.8'

services:
  postgres:
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory='/logs'"]
    volumes:
      - "./code/postgres/crontab:/etc/cron.d/custom"
      - "./code/postgres/dump_db.sh:/usr/local/bin/dump_db.sh"
      - "./data/postgres/dumps:/dumps"
      - "./data/postgres/logs:/logs"
    restart: always

  django:
    volumes:
      - "./data/django/logs:/logs"
    restart: always

  nginx:
    volumes:
      - "./src/nginx/nginx.override.logs.conf:/etc/nginx/nginx.override.logs.conf"
    restart: always
