version: '3.8'

services:
  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql/data/pgdata"

  django:
    image: planning/django:${VERSION}
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - "./src/django:/code"
      - "./docs:/docs"
    depends_on:
      - postgres

  nginx:
    image: planning/nginx:${VERSION}
    volumes:
      - "./src/django/media:/media:ro"
      - "./src/django/static:/static:ro"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - django
